
<%
	Response.Charset = "UTF-8"
	response.ContentType = "application/vnd.ms-excel" 
	response.AddHeader "Content-Disposition", "attachment; filename=ConsBasicasAnexo.xls"

response.Write("MIME-Version: 1.0" &vbCr) 
response.Write("X-Document-Type: Workbook" &vbCr) 
response.Write("Content-Type: multipart/related; boundary=3D""----=_NextPart_ExcelWorkbook"""&vbCr) 
response.Write(""&vbCr) 
response.Write("------=_NextPart_ExcelWorkbook" &vbCr) 
response.Write("Content-Location: books.xls" &vbCr) 
response.Write("Content-Transfer-Encoding: quoted-printable" &vbCr) 
response.Write("Content-Type: text/html; charset=3D""us-ascii""" &vbCr) 
response.Write("" &vbCr) 
response.Write("<html xmlns:x=3D""urn:schemas-microsoft-com:office:excel"">" &vbCr) 
response.Write("<head>" &vbCr) 
response.Write("<meta name=3D""Excel Workbook Frameset"">" &vbCr) 
response.Write("<xml>" &vbCr) 
      response.Write("<x:ExcelWorkbook>" &vbCr) 
            response.Write("<x:ExcelWorksheets>" &vbCr) 
                  response.Write("<x:ExcelWorksheet>" &vbCr)
                        response.Write("<x:Name>First Sheet</x:Name>" &vbCr) 
                        response.Write("<x:WorksheetSource HRef=3D""sheet1.htm""/>" &vbCr) 
                  response.Write("</x:ExcelWorksheet>" &vbCr) 
                  response.Write("<x:ExcelWorksheet>" &vbCr) 
                        response.Write("<x:Name>Second Sheet</x:Name>" &vbCr) 
                        response.Write("<x:WorksheetSource HRef=3D""sheet2.htm""/>" &vbCr) 
                  response.Write("</x:ExcelWorksheet>" &vbCr) 
            response.Write("</x:ExcelWorksheets>" &vbCr) 
      response.Write("</x:ExcelWorkbook>" &vbCr) 
response.Write("</xml>" &vbCr) 
response.Write("</head>" &vbCr) 
response.Write("</html>" &vbCr) 
response.Write(""&vbCr) 
response.Write("------=_NextPart_ExcelWorkbook" &vbCr) 
response.Write("Content-Location: sheet1.htm" &vbCr)
response.Write("Content-Transfer-Encoding: quoted-printable" &vbCr)
response.Write("Content-Type: text/html; charset=3D""us-ascii""" &vbCr) 
response.Write(""&vbCr) 
response.Write("<table>" &vbCr) 
      response.Write("<tr>" &vbCr) 
            response.Write("<td>1</td>" &vbCr) 
            response.Write("<td>2</td>" &vbCr) 
            response.Write("<td>3</td>" &vbCr) 
      response.Write("</tr>" &vbCr) 
      response.Write("<tr>" &vbCr) 
            response.Write("<td>4</td>" &vbCr) 
            response.Write("<td>5</td>" &vbCr) 
            response.Write("<td>6</td>" &vbCr)
      response.Write("</tr>" &vbCr) 
response.Write("</table>" &vbCr) 
response.Write(""&vbCr) 
response.Write("------=_NextPart_ExcelWorkbook" &vbCr) 
response.Write("Content-Location: sheet2.htm" &vbCr) 
response.Write("Content-Transfer-Encoding: quoted-printable" &vbCr) 
response.Write("Content-Type: text/html; charset=3D""us-ascii""" &vbCr) 
response.Write(""&vbCr) 
response.Write("<table>" &vbCr) 
      response.Write("<tr>" &vbCr)
            response.Write("<td>a</td>" &vbCr) 
            response.Write("<td>b</td>" &vbCr) 
            response.Write("<td>c</td>" &vbCr) 
      response.Write("</tr>" &vbCr) 
      response.Write("<tr>" &vbCr)
            response.Write("<td>d</td>" &vbCr) 
            response.Write("<td>e</td>" &vbCr) 
            response.Write("<td>f</td>" &vbCr) 
      response.Write("</tr>" &vbCr) 
response.Write("</table>" &vbCr) 
response.Write("------=_NextPart_ExcelWorkbook--" &vbCr) 
%>

